# CMake generated Testfile for 
# Source directory: /var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-common
# Build directory: /var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-opm-common
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
  add_test(cppcheck+opm/common/data/SimulationDataContainer.cpp "bin/cppcheck-test.sh" "/usr/bin/cppcheck" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-common/opm/common/data/SimulationDataContainer.cpp" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-common" "-I" "/usr/include")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
  add_test(cppcheck+opm/common/OpmLog/CounterLog.cpp "bin/cppcheck-test.sh" "/usr/bin/cppcheck" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-common/opm/common/OpmLog/CounterLog.cpp" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-common" "-I" "/usr/include")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
  add_test(cppcheck+opm/common/OpmLog/EclipsePRTLog.cpp "bin/cppcheck-test.sh" "/usr/bin/cppcheck" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-common/opm/common/OpmLog/EclipsePRTLog.cpp" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-common" "-I" "/usr/include")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
  add_test(cppcheck+opm/common/OpmLog/LogBackend.cpp "bin/cppcheck-test.sh" "/usr/bin/cppcheck" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-common/opm/common/OpmLog/LogBackend.cpp" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-common" "-I" "/usr/include")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
  add_test(cppcheck+opm/common/OpmLog/Logger.cpp "bin/cppcheck-test.sh" "/usr/bin/cppcheck" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-common/opm/common/OpmLog/Logger.cpp" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-common" "-I" "/usr/include")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
  add_test(cppcheck+opm/common/OpmLog/LogUtil.cpp "bin/cppcheck-test.sh" "/usr/bin/cppcheck" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-common/opm/common/OpmLog/LogUtil.cpp" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-common" "-I" "/usr/include")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
  add_test(cppcheck+opm/common/OpmLog/OpmLog.cpp "bin/cppcheck-test.sh" "/usr/bin/cppcheck" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-common/opm/common/OpmLog/OpmLog.cpp" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-common" "-I" "/usr/include")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
  add_test(cppcheck+opm/common/OpmLog/StreamLog.cpp "bin/cppcheck-test.sh" "/usr/bin/cppcheck" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-common/opm/common/OpmLog/StreamLog.cpp" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-common" "-I" "/usr/include")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
  add_test(cppcheck+opm/common/OpmLog/TimerLog.cpp "bin/cppcheck-test.sh" "/usr/bin/cppcheck" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-common/opm/common/OpmLog/TimerLog.cpp" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-common" "-I" "/usr/include")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
  add_test(cppcheck+opm/core/utility/parameters/Parameter.cpp "bin/cppcheck-test.sh" "/usr/bin/cppcheck" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-common/opm/core/utility/parameters/Parameter.cpp" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-common" "-I" "/usr/include")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
  add_test(cppcheck+opm/core/utility/parameters/ParameterGroup.cpp "bin/cppcheck-test.sh" "/usr/bin/cppcheck" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-common/opm/core/utility/parameters/ParameterGroup.cpp" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-common" "-I" "/usr/include")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
  add_test(cppcheck+opm/core/utility/parameters/ParameterTools.cpp "bin/cppcheck-test.sh" "/usr/bin/cppcheck" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-common/opm/core/utility/parameters/ParameterTools.cpp" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-common" "-I" "/usr/include")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
