#ifndef OPM_GENERATED_OPM_VERSION_HEADER_INCLUDED
#define OPM_GENERATED_OPM_VERSION_HEADER_INCLUDED
#define PROJECT_VERSION_NAME "2018.04-pre"
#define PROJECT_VERSION_HASH "58f5115"
#define PROJECT_VERSION "2018.04-pre (58f5115)"
#endif // OPM_GENERATED_OPM_VERSION_HEADER_INCLUDED
