# CMake generated Testfile for 
# Source directory: /var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output
# Build directory: /var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-opm-output
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
  add_test(cppcheck+opm/test_util/summaryIntegrationTest.cpp "bin/cppcheck-test.sh" "/usr/bin/cppcheck" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output/opm/test_util/summaryIntegrationTest.cpp" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output" "-I" "/usr/include" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/install/include")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
  add_test(cppcheck+opm/test_util/summaryRegressionTest.cpp "bin/cppcheck-test.sh" "/usr/bin/cppcheck" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output/opm/test_util/summaryRegressionTest.cpp" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output" "-I" "/usr/include" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/install/include")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
  add_test(cppcheck+opm/test_util/summaryComparator.cpp "bin/cppcheck-test.sh" "/usr/bin/cppcheck" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output/opm/test_util/summaryComparator.cpp" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output" "-I" "/usr/include" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/install/include")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
  add_test(cppcheck+opm/test_util/EclFilesComparator.cpp "bin/cppcheck-test.sh" "/usr/bin/cppcheck" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output/opm/test_util/EclFilesComparator.cpp" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output" "-I" "/usr/include" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/install/include")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
  add_test(cppcheck+opm/output/eclipse/EclipseGridInspector.cpp "bin/cppcheck-test.sh" "/usr/bin/cppcheck" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output/opm/output/eclipse/EclipseGridInspector.cpp" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output" "-I" "/usr/include" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/install/include")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
  add_test(cppcheck+opm/output/eclipse/EclipseIO.cpp "bin/cppcheck-test.sh" "/usr/bin/cppcheck" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output/opm/output/eclipse/EclipseIO.cpp" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output" "-I" "/usr/include" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/install/include")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
  add_test(cppcheck+opm/output/eclipse/LinearisedOutputTable.cpp "bin/cppcheck-test.sh" "/usr/bin/cppcheck" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output/opm/output/eclipse/LinearisedOutputTable.cpp" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output" "-I" "/usr/include" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/install/include")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
  add_test(cppcheck+opm/output/eclipse/RestartIO.cpp "bin/cppcheck-test.sh" "/usr/bin/cppcheck" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output/opm/output/eclipse/RestartIO.cpp" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output" "-I" "/usr/include" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/install/include")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
  add_test(cppcheck+opm/output/eclipse/Summary.cpp "bin/cppcheck-test.sh" "/usr/bin/cppcheck" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output/opm/output/eclipse/Summary.cpp" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output" "-I" "/usr/include" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/install/include")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
  add_test(cppcheck+opm/output/eclipse/Tables.cpp "bin/cppcheck-test.sh" "/usr/bin/cppcheck" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output/opm/output/eclipse/Tables.cpp" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output" "-I" "/usr/include" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/install/include")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
  add_test(cppcheck+opm/output/eclipse/RegionCache.cpp "bin/cppcheck-test.sh" "/usr/bin/cppcheck" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output/opm/output/eclipse/RegionCache.cpp" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output" "-I" "/usr/include" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/install/include")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
  add_test(cppcheck+opm/output/data/Solution.cpp "bin/cppcheck-test.sh" "/usr/bin/cppcheck" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output/opm/output/data/Solution.cpp" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output" "-I" "/usr/include" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/install/include")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
  add_test(cppcheck+test_util/compareECL.cpp "bin/cppcheck-test.sh" "/usr/bin/cppcheck" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output/test_util/compareECL.cpp" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output" "-I" "/usr/include" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/install/include")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
  add_test(cppcheck+test_util/compareSummary.cpp "bin/cppcheck-test.sh" "/usr/bin/cppcheck" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output/test_util/compareSummary.cpp" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output" "-I" "/usr/include" "-I" "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/install/include")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Aa][Nn][Aa][Ll][Yy][Zz][Ee]|[Cc][Pp][Pp][Cc][Hh][Ee][Cc][Kk])$")
