#ifndef OPM_GENERATED_OPM_VERSION_HEADER_INCLUDED
#define OPM_GENERATED_OPM_VERSION_HEADER_INCLUDED
#define PROJECT_VERSION_NAME "2018.04-pre"
#define PROJECT_VERSION_HASH "25ba406"
#define PROJECT_VERSION "2018.04-pre (25ba406)"
#endif // OPM_GENERATED_OPM_VERSION_HEADER_INCLUDED
