#define HAS_ATTRIBUTE_UNUSED 1
#define HAS_ATTRIBUTE_DEPRECATED 1
#define HAS_ATTRIBUTE_DEPRECATED_MSG 1
#define HAVE_ARRAY 1
/* #undef HAVE_BOOST_MAKE_SHARED_HPP */
/* #undef HAVE_BOOST_SHARED_PTR_HPP */
#define HAVE_DUNE_BOOST 1
/* #undef HAVE_GMP */
#define HAVE_MAKE_SHARED 1
#define HAVE_MPI 1
#define HAVE_NULLPTR 1
#define HAVE_STATIC_ASSERT 1
#define HAVE_SHARED_PTR 1
#define MPI_2 1
#define SHARED_PTR_HEADER <memory>
#define SHARED_PTR_NAMESPACE std
#define HAVE_TYPE_TRAITS 1
#define HAVE_TR1_TUPLE 1
#define HAVE_TUPLE 1
#define HAVE_CXA_DEMANGLE 1
/* #undef HAVE_ALGLIB */
/* #undef HAVE_UG */
/* #undef HAVE_DUNE_FEM */
/* #undef HAVE_GRIDTYPE */
/* #undef HAVE_GRAPE */
/* #undef HAVE_PSURFACE */
/* #undef HAVE_AMIRAMESH */
/* #undef HAVE_ALBERTA */
/* #undef HAVE_STDINT_H */
#define DUNE_GRID_EXPERIMENTAL_GRID_EXTENSIONS 1
/* #undef HAVE_BOOST_FUSION */
/* #undef HAVE_MEM_USAGE_T_EXPANSIONS */
/* #undef HAVE_PARDISO */
#define HAVE_BOOST 1
/* #undef HAVE_PARMETIS */
/* #undef HAVE_SUPERLU */
#define HAVE_UMFPACK 1
/* #undef SUPERLU_MIN_VERSION_4_3 */
/* #undef SUPERLU_POST_2005_VERSION */
#define HAVE_OPM_PARSER 1
/* #undef HAVE_REGEX */
#define HAVE_ERT 1
#define DUNE_GRID_VERSION_MAJOR 2
#define DUNE_GRID_VERSION_MINOR 5
#define DUNE_GRID_VERSION_REVISION 0
#define DUNE_GEOMETRY_VERSION_MAJOR 2
#define DUNE_GEOMETRY_VERSION_MINOR 5
#define DUNE_GEOMETRY_VERSION_REVISION 0
#define DUNE_COMMON_VERSION_MAJOR 2
#define DUNE_COMMON_VERSION_MINOR 5
#define DUNE_COMMON_VERSION_REVISION 0
#define HAVE_DUNE_ISTL 1
#define HAVE_ZOLTAN 1
#define HAVE_DUNE_GRID_CHECKS 0
#define HAVE_DYNAMIC_BOOST_TEST 1
