#ifndef OPM_GENERATED_OPM_VERSION_HEADER_INCLUDED
#define OPM_GENERATED_OPM_VERSION_HEADER_INCLUDED
#define PROJECT_VERSION_NAME "2018.04-pre"
#define PROJECT_VERSION_HASH "ec58bfb"
#define PROJECT_VERSION "2018.04-pre (ec58bfb)"
#endif // OPM_GENERATED_OPM_VERSION_HEADER_INCLUDED
