#define HAVE_OPM_PARSER 1
/* #undef HAVE_REGEX */
#define HAVE_ERT 1
#define HAS_ATTRIBUTE_UNUSED 1
#define HAS_ATTRIBUTE_DEPRECATED 1
#define HAS_ATTRIBUTE_DEPRECATED_MSG 1
#define HAVE_ARRAY 1
/* #undef HAVE_BOOST_MAKE_SHARED_HPP */
/* #undef HAVE_BOOST_SHARED_PTR_HPP */
#define HAVE_DUNE_BOOST 1
/* #undef HAVE_GMP */
#define HAVE_MAKE_SHARED 1
#define HAVE_MPI 1
#define HAVE_NULLPTR 1
#define HAVE_STATIC_ASSERT 1
#define HAVE_SHARED_PTR 1
#define MPI_2 1
#define SHARED_PTR_HEADER <memory>
#define SHARED_PTR_NAMESPACE std
#define HAVE_TYPE_TRAITS 1
#define HAVE_TR1_TUPLE 1
#define HAVE_TUPLE 1
#define HAVE_CXA_DEMANGLE 1
#define HAVE_VALGRIND 1
#define HAVE_FINAL 1
#define DUNE_COMMON_VERSION_MAJOR 2
#define DUNE_COMMON_VERSION_MINOR 5
#define DUNE_COMMON_VERSION_REVISION 0
#define HAVE_DYNAMIC_BOOST_TEST 1
