#ifndef OPM_GENERATED_OPM_VERSION_HEADER_INCLUDED
#define OPM_GENERATED_OPM_VERSION_HEADER_INCLUDED
#define PROJECT_VERSION_NAME "2018.04-pre"
#define PROJECT_VERSION_HASH "9e3afc1"
#define PROJECT_VERSION "2018.04-pre (9e3afc1)"
#endif // OPM_GENERATED_OPM_VERSION_HEADER_INCLUDED
