# CMake generated Testfile for 
# Source directory: /var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms
# Build directory: /var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(art2dgf "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--plain" "art2dgf" "data/fracture-raw.art")
set_tests_properties(art2dgf PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(waterair_pvs_ni "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "waterair_pvs_ni" "--grid-global-refinements=1")
set_tests_properties(waterair_pvs_ni PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(lens_immiscible_vcfv_ad "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "lens_immiscible_vcfv_ad" "--end-time=3000")
set_tests_properties(lens_immiscible_vcfv_ad PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(lens_immiscible_vcfv_fd "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "lens_immiscible_vcfv_fd" "--end-time=3000")
set_tests_properties(lens_immiscible_vcfv_fd PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(lens_immiscible_ecfv_ad "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "lens_immiscible_ecfv_ad" "--end-time=3000")
set_tests_properties(lens_immiscible_ecfv_ad PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(co2injection_flash_ni_vcfv "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "co2injection_flash_ni_vcfv")
set_tests_properties(co2injection_flash_ni_vcfv PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(co2injection_flash_ni_ecfv "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "co2injection_flash_ni_ecfv")
set_tests_properties(co2injection_flash_ni_ecfv PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(co2injection_flash_vcfv "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "co2injection_flash_vcfv")
set_tests_properties(co2injection_flash_vcfv PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(co2injection_flash_ecfv "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "co2injection_flash_ecfv")
set_tests_properties(co2injection_flash_ecfv PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(co2injection_ncp_ni_vcfv "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "co2injection_ncp_ni_vcfv")
set_tests_properties(co2injection_ncp_ni_vcfv PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(co2injection_pvs_ni_vcfv "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "co2injection_pvs_ni_vcfv")
set_tests_properties(co2injection_pvs_ni_vcfv PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(co2injection_ncp_vcfv "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "co2injection_ncp_vcfv")
set_tests_properties(co2injection_ncp_vcfv PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(co2injection_pvs_vcfv "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "co2injection_pvs_vcfv")
set_tests_properties(co2injection_pvs_vcfv PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(co2injection_immiscible_ni_vcfv "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "co2injection_immiscible_ni_vcfv")
set_tests_properties(co2injection_immiscible_ni_vcfv PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(co2injection_immiscible_vcfv "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "co2injection_immiscible_vcfv")
set_tests_properties(co2injection_immiscible_vcfv PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(co2injection_immiscible_ecfv "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "co2injection_immiscible_ecfv")
set_tests_properties(co2injection_immiscible_ecfv PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(co2injection_ncp_ecfv "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "co2injection_ncp_ecfv")
set_tests_properties(co2injection_ncp_ecfv PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(co2injection_pvs_ecfv "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "co2injection_pvs_ecfv")
set_tests_properties(co2injection_pvs_ecfv PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(co2injection_immiscible_ni_ecfv "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "co2injection_immiscible_ni_ecfv")
set_tests_properties(co2injection_immiscible_ni_ecfv PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(co2injection_ncp_ni_ecfv "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "co2injection_ncp_ni_ecfv")
set_tests_properties(co2injection_ncp_ni_ecfv PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(co2injection_pvs_ni_ecfv "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "co2injection_pvs_ni_ecfv")
set_tests_properties(co2injection_pvs_ni_ecfv PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(powerinjection_forchheimer_fd "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "powerinjection_forchheimer_fd")
set_tests_properties(powerinjection_forchheimer_fd PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(powerinjection_forchheimer_ad "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "powerinjection_forchheimer_ad")
set_tests_properties(powerinjection_forchheimer_ad PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(powerinjection_darcy_fd "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "powerinjection_darcy_fd")
set_tests_properties(powerinjection_darcy_fd PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(powerinjection_darcy_ad "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "powerinjection_darcy_ad")
set_tests_properties(powerinjection_darcy_ad PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(cuvette_pvs "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "cuvette_pvs")
set_tests_properties(cuvette_pvs PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(infiltration_pvs "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "infiltration_pvs")
set_tests_properties(infiltration_pvs PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(lens_richards_vcfv "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "lens_richards_vcfv")
set_tests_properties(lens_richards_vcfv PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(lens_richards_ecfv "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "lens_richards_ecfv")
set_tests_properties(lens_richards_ecfv PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(obstacle_immiscible "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "obstacle_immiscible")
set_tests_properties(obstacle_immiscible PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(obstacle_ncp "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "obstacle_ncp")
set_tests_properties(obstacle_ncp PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(obstacle_pvs "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "obstacle_pvs")
set_tests_properties(obstacle_pvs PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(outflow_pvs "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "outflow_pvs")
set_tests_properties(outflow_pvs PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(diffusion_flash "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "diffusion_flash")
set_tests_properties(diffusion_flash PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(diffusion_ncp "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "diffusion_ncp")
set_tests_properties(diffusion_ncp PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(diffusion_pvs "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "diffusion_pvs")
set_tests_properties(diffusion_pvs PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(groundwater_immiscible "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "groundwater_immiscible")
set_tests_properties(groundwater_immiscible PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(reservoir_blackoil_vcfv "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "reservoir_blackoil_vcfv" "--end-time=8750000")
set_tests_properties(reservoir_blackoil_vcfv PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(reservoir_blackoil_ecfv "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "reservoir_blackoil_ecfv" "--end-time=8750000")
set_tests_properties(reservoir_blackoil_ecfv PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(reservoir_ncp_vcfv "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "reservoir_ncp_vcfv" "--end-time=8750000")
set_tests_properties(reservoir_ncp_vcfv PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(reservoir_ncp_ecfv "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "reservoir_ncp_ecfv" "--end-time=8750000")
set_tests_properties(reservoir_ncp_ecfv PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(test_propertysystem "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--plain" "test_propertysystem")
set_tests_properties(test_propertysystem PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(test_quadrature "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--plain" "test_quadrature")
set_tests_properties(test_quadrature PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(co2injection_ncp_ni_ecfv_parallel "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--parallel-simulation=4" "co2injection_ncp_ni_ecfv")
set_tests_properties(co2injection_ncp_ni_ecfv_parallel PROPERTIES  PROCESSORS "4" WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(obstacle_immiscible_parallel "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--parallel-simulation=4" "obstacle_immiscible" "--end-time=1" "--initial-time-step-size=1")
set_tests_properties(obstacle_immiscible_parallel PROPERTIES  PROCESSORS "4" WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(lens_immiscible_vcfv_fd_parallel "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--parallel-simulation=4" "lens_immiscible_vcfv_fd" "--end-time=250" "--initial-time-step-size=250")
set_tests_properties(lens_immiscible_vcfv_fd_parallel PROPERTIES  PROCESSORS "4" WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(lens_immiscible_vcfv_ad_parallel "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--parallel-simulation=4" "lens_immiscible_vcfv_ad" "--end-time=250" "--initial-time-step-size=250")
set_tests_properties(lens_immiscible_vcfv_ad_parallel PROPERTIES  PROCESSORS "4" WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(lens_immiscible_ecfv_ad_parallel "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--parallel-simulation=4" "lens_immiscible_ecfv_ad" "--end-time=250" "--initial-time-step-size=250")
set_tests_properties(lens_immiscible_ecfv_ad_parallel PROPERTIES  PROCESSORS "4" WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(obstacle_immiscible_parameters "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--parameters" "obstacle_immiscible")
set_tests_properties(obstacle_immiscible_parameters PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(obstacle_pvs_restart "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--restart" "obstacle_pvs" "--pvs-verbosity=2" "--end-time=30000")
set_tests_properties(obstacle_pvs_restart PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
add_test(tutorial1 "/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/bin/runtest.sh" "--simulation" "tutorial1")
set_tests_properties(tutorial1 PROPERTIES  WORKING_DIRECTORY "/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-ewoms")
