#ifndef OPM_GENERATED_OPM_VERSION_HEADER_INCLUDED
#define OPM_GENERATED_OPM_VERSION_HEADER_INCLUDED
#define PROJECT_VERSION_NAME ""
#define PROJECT_VERSION_HASH "e2e11c4"
#define PROJECT_VERSION " (e2e11c4)"
#endif // OPM_GENERATED_OPM_VERSION_HEADER_INCLUDED
